name: Push Docker image to Amazon ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-2

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region YOUR_AWS_REGION | docker login --username AWS --password-stdin 388123136160.dkr.ecr.us-east-2.amazonaws.com
        
    - name: Build Docker image
      run: docker build -t CRISPResso2_test .

    - name: Tag Docker image with version
      run: docker tag CRISPResso2_test:latest 388123136160.dkr.ecr.us-east-2.amazonaws.com/CRISPResso2_test:latest

    - name: Push Docker image to Amazon ECR
      run: docker push 388123136160.dkr.ecr.us-east-2.amazonaws.com/CRISPResso2_test:latest
