name: Push Docker image to Amazon ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Login to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
        run: |
          export TOKEN=$(aws ecr get-login-password --region us-east-2)
    
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
        run: |
          script -e -c echo $TOKEN | docker login -u AWS --password-stdin 388123136160.dkr.ecr.us-east-2.amazonaws.com
          docker build -t CRISPResso2_test .
          docker tag CRISPResso2_test:latest 388123136160.dkr.ecr.us-east-2.amazonaws.com/crispresso2_test:latest
          docker push 388123136160.dkr.ecr.us-east-2.amazonaws.com/crispresso2_test:latest
